name: Feature request
description: Suggest a feature to add to KitchenOwl
title: "Feature request: "
labels: ["enhancement"]
projects: ["TomBursch/1"]
body:
  - type: textarea
    id: description
    attributes:
      label: "What's the feature 🧐"
      placeholder: "Guess what my roomates want to eat"
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: "Extra information and references"
      placeholder: |
        - I tried `docker run something` and it doesn't work
        - That [url](https://github.com/TomBursch/kitchenowl/) is interesting

