name: Release Docs
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: pip install -r docs/requirements.txt
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "support@kitchenowl.org"
      - name: Build Docs Website
        run: mike deploy --push --update-aliases ${{ github.ref_name }} latest
        working-directory: docs
